# parameters.xml

-
  branches:
    only:
      - master
      
  version: 0.6.0
  
  skip_tags: true

  image: Visual Studio 2015
      
  init:
    - git config --global core.autocrlf input
  
  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: AssemblyInfo.*
    patch: true

  configuration: Release

  before_build:
    - appveyor-retry nuget restore

  build:
    parallel: true
    
  artifacts:
    - path: ParametersXml
      name: ParametersXml
      type: zip

  on_failure:
    - ps: Update-AppveyorBuild -Version "$($Env:APPVEYOR_BUILD_VERSION).$($Env:APPVEYOR_BUILD_NUMBER)-fail"
  
  cache:
    - packages  -> **\packages.config